

const CATEGORIAS = [
  { id: "Notebooks",         nombre: "Notebooks",         imagen: "../img/productos/ASUS ROG Strix G16 (G614JV).png" },
  { id: "Tarjetas-Graficas", nombre: "Tarjetas Gráficas", imagen: "../img/productos/asus-dual-rtx-4070.png" },
  { id: "Monitores",         nombre: "Monitores",         imagen: "../img/productos/lg-ultragear-27gp850.png" },
  { id: "Perifericos",       nombre: "Perifericos",       imagen: "../img/productos/logitech-g-pro-x-superlight-2.png" },
  { id: "Consolas",          nombre: "Consolas",          imagen: "../img/productos/playstation-5.png" },
  { id: "almacenamiento",    nombre: "Almacenamiento",    imagen: "../img/productos/samsung-980-pro.png" },
  { id: "Procesadores",      nombre: "Procesadores",      imagen: "../img/productos/intel-core-i7-13650hx.png" },
  { id: "Placas-Madre",      nombre: "Placas Madre",      imagen: "../img/productos/msi-b650.toml" },
  { id: "Memorias-RAM",      nombre: "Memorias RAM",      imagen: "../img/productos/corsair-vengeance-pro-32gb.jpg" },
  { id: "Fuentes-de-Poder",  nombre: "Fuentes de Poder",  imagen: "../img/productos/corsair-rm750x.jpg" },
  { id: "Gabinetes",         nombre: "Gabinetes",         imagen: "../img/productos/Corsair Carbide Series 2500.jpg" },
  { id: "Refrigeracion",     nombre: "Refrigeración",     imagen: "../img/productos/corsair-liquid-cooling.jpg" },
  { id: "PCs-Armados",       nombre: "PCs Armados",       imagen: "" },
];

/* -----------------------------------------------------------------
   PRODUCTOS
   Un producto real por categoría, con especificaciones reales
   (modelo, componentes, características técnicas). Los precios son
   una referencia aproximada en pesos chilenos (CLP), no un precio
   oficial vigente. "destacado: true" marca los que aparecen en la
   sección "Productos destacados" de Inicio.
   ----------------------------------------------------------------- */
const PRODUCTOS = [
  {
    id: 1,
    nombre: "ASUS ROG Strix G16 (G614JV)",
    categoria: "Notebooks",
    marca: "asus",
    precioNormal: 1590000,
    precioDescuento: 1390000,
    stock: 6,
    destacado: true,
    imagen: "../img/productos/ASUS ROG Strix G16 (G614JV).png",
    imagenes: [
      "../img/productos/ASUS ROG Strix G16 (G614JV).png",
      "../img/productos/ASUS ROG Strix G16 (G614JV).png",
    ],
    especificaciones: [
      "Procesador Intel Core i7-13650HX (14 núcleos, hasta 4.9 GHz)",
      "Tarjeta gráfica NVIDIA GeForce RTX 4060 8GB GDDR6",
      "16 GB RAM DDR5 4800MHz",
      "SSD NVMe 1TB",
      "Pantalla 16\" FHD+ 165Hz",
    ],
    resenas: [
      { autor: "Camila", puntuacion: 5, comentario: "Rinde increíble en juegos AAA y en edición de video.", fecha: "2026-05-02" },
      { autor: "Tomás",  puntuacion: 4, comentario: "Se calienta un poco bajo carga máxima en verano.", fecha: "2026-04-18" },
    ],
  },
  {
    id: 2,
    nombre: "ASUS Dual GeForce RTX 4070 OC 12GB",
    categoria: "Tarjetas-Graficas",
    marca: "asus",
    precioNormal: 699990,
    precioDescuento: 619990,
    stock: 4,
    destacado: true,
    imagen: "../img/productos/asus-dual-rtx-4070.png",
    imagenes: ["../img/productos/asus-dual-rtx-4070.png", "../img/productos/asus-dual-rtx-4070-2.png"],
    especificaciones: [
      "12 GB de memoria GDDR6X",
      "Arquitectura NVIDIA Ada Lovelace",
      "Ray tracing de 3ra generación y DLSS 3",
      "2 ventiladores axiales, diseño de doble slot",
      "Conectores: 1x HDMI 2.1, 3x DisplayPort 1.4a",
    ],
    resenas: [
      { autor: "Ignacio",   puntuacion: 5, comentario: "Corre todo en ultra a 1440p sin problema.", fecha: "2026-06-01" },
      { autor: "Valentina", puntuacion: 4, comentario: "Es grande, revisa que te quepa en el gabinete.", fecha: "2026-05-20" },
    ],
  },
  {
    id: 3,
    nombre: "LG UltraGear 27GP850-B 27\" QHD 165Hz",
    categoria: "Monitores",
    marca: "lg",
    precioNormal: 379990,
    precioDescuento: null,
    stock: 8,
    destacado: false,
    imagen: "../img/productos/lg-ultragear-27gp850.jpg",
    imagenes: ["../img/productos/lg-ultragear-27gp850.jpg"],
    especificaciones: [
      "Panel Nano IPS 27\" QHD (2560x1440)",
      "Tasa de refresco 165Hz, 1ms (GtG)",
      "NVIDIA G-SYNC Compatible / AMD FreeSync Premium",
      "HDR10",
    ],
    resenas: [
      { autor: "Renata", puntuacion: 5, comentario: "Colores muy fieles, ideal para diseño y juegos.", fecha: "2026-05-27" },
    ],
  },
  {
    id: 4,
    nombre: "Logitech G Pro X Superlight 2",
    categoria: "Perifericos",
    marca: "logitech",
    precioNormal: 129990,
    precioDescuento: 109990,
    stock: 15,
    destacado: true,
    imagen: "../img/productos/logitech-g-pro-x-superlight-2.png",
    imagenes: ["../img/productos/logitech-g-pro-x-superlight-2.png"],
    especificaciones: [
      "Peso: 60 gramos",
      "Sensor HERO 2 de 32.000 DPI",
      "Conexión inalámbrica LIGHTSPEED",
      "Hasta 95 horas de batería",
    ],
    resenas: [
      { autor: "Martina",  puntuacion: 5, comentario: "Súper liviano, ideal para juegos competitivos.", fecha: "2026-06-10" },
      { autor: "Benjamín", puntuacion: 4, comentario: "Excelente, aunque el precio es alto.", fecha: "2026-06-05" },
    ],
  },
  {
    id: 5,
    nombre: "PlayStation 5 Slim",
    categoria: "Consolas",
    marca: "sony",
    precioNormal: 549990,
    precioDescuento: 499990,
    stock: 3,
    destacado: true,
    imagen: "../img/productos/playstation-5-slim.png",
    imagenes: ["../img/productos/playstation-5-slim.png", "../img/productos/playstation-5-slim-2.png"],
    especificaciones: [
      "SSD ultrarrápido de 1TB",
      "Resolución 4K a hasta 120fps",
      "Ray tracing por hardware",
      "Incluye un control DualSense",
    ],
    resenas: [
      { autor: "Diego", puntuacion: 5, comentario: "Los tiempos de carga son casi instantáneos.", fecha: "2026-04-30" },
    ],
  },
  {
    id: 6,
    nombre: "Samsung 990 PRO 1TB NVMe SSD",
    categoria: "almacenamiento",
    marca: "samsung",
    precioNormal: 119990,
    precioDescuento: 99990,
    stock: 20,
    destacado: false,
    imagen: "../img/productos/samsung-990-pro-1tb.png",
    imagenes: ["../img/productos/samsung-990-pro-1tb.png"],
    especificaciones: [
      "Interfaz PCIe 4.0 NVMe, formato M.2",
      "Velocidad de lectura secuencial hasta 7.450 MB/s",
      "Velocidad de escritura secuencial hasta 6.900 MB/s",
      "Incluye disipador de calor opcional",
    ],
    resenas: [],
  },
  {
    id: 7,
    nombre: "AMD Ryzen 7 7800X3D",
    categoria: "Procesadores",
    marca: "amd",
    precioNormal: 429990,
    precioDescuento: 389990,
    stock: 10,
    destacado: false,
    imagen: "../img/productos/amd-ryzen-7-7800x3d.png",
    imagenes: ["../img/productos/amd-ryzen-7-7800x3d.png"],
    especificaciones: [
      "8 núcleos / 16 hilos",
      "Frecuencia base 4.2 GHz, boost hasta 5.0 GHz",
      "Tecnología AMD 3D V-Cache (96 MB caché L3)",
      "Socket AM5",
    ],
    resenas: [
      { autor: "Josefa", puntuacion: 5, comentario: "El mejor procesador para gaming puro que he tenido.", fecha: "2026-03-11" },
    ],
  },
  {
    id: 8,
    nombre: "ASUS ROG Strix B650-A Gaming WiFi",
    categoria: "Placas-Madre",
    marca: "asus",
    precioNormal: 249990,
    precioDescuento: null,
    stock: 7,
    destacado: false,
    imagen: "../img/productos/asus-rog-strix-b650-a.png",
    imagenes: ["../img/productos/asus-rog-strix-b650-a.png", "../img/productos/asus-rog-strix-b650-a-2.png"],
    especificaciones: [
      "Socket AM5, chipset B650",
      "Soporta hasta 128 GB DDR5",
      "2x ranuras M.2 PCIe 4.0",
      "WiFi 6E y Bluetooth 5.3 integrados",
    ],
    resenas: [],
  },
  {
    id: 9,
    nombre: "Corsair Vengeance RGB DDR5 32GB (2x16GB) 6000MHz",
    categoria: "Memorias-RAM",
    marca: "corsair",
    precioNormal: 149990,
    precioDescuento: 129990,
    stock: 25,
    destacado: false,
    imagen: "../img/productos/corsair-vengeance-rgb-ddr5-32gb.png",
    imagenes: ["../img/productos/corsair-vengeance-rgb-ddr5-32gb.png", "../img/productos/corsair-vengeance-rgb-ddr5-32gb-2.png"],
    especificaciones: [
      "Kit dual channel 2x16GB",
      "Velocidad 6000MHz, latencia CL36",
      "Iluminación RGB dinámica por módulo",
      "Compatible con Intel XMP 3.0",
    ],
    resenas: [
      { autor: "Fernanda", puntuacion: 5, comentario: "Fácil de configurar el XMP y se ve espectacular.", fecha: "2026-06-14" },
    ],
  },
  {
    id: 10,
    nombre: "Corsair RM850x 850W 80+ Gold",
    categoria: "Fuentes-de-Poder",
    marca: "corsair",
    precioNormal: 139990,
    precioDescuento: null,
    stock: 12,
    destacado: false,
    imagen: "../img/productos/corsair-rm850x.png",
    imagenes: ["../img/productos/corsair-rm850x.png", "../img/productos/corsair-rm850x-2.png"],
    especificaciones: [
      "Potencia 850W, certificación 80 PLUS Gold",
      "Modular full (todos los cables desconectables)",
      "Ventilador de 135mm con modo silencioso zero RPM",
      "Garantía de 10 años",
    ],
    resenas: [],
  },
  {
    id: 11,
    nombre: "NZXT H510 Flow",
    categoria: "Gabinetes",
    marca: "nzxt",
    precioNormal: 89990,
    precioDescuento: 74990,
    stock: 14,
    destacado: false,
    imagen: "../img/productos/nzxt-h510-flow-2.png",
    imagenes: ["../img/productos/nzxt-h510-flow.png", "../img/productos/nzxt-h510-flow-2.png"],
    especificaciones: [
      "Formato Mid-Tower ATX",
      "Panel frontal perforado para mejor flujo de aire",
      "Panel lateral de vidrio templado",
      "Soporta hasta 6 ventiladores y radiadores de 280mm",
    ],
    resenas: [],
  },
  {
    id: 12,
    nombre: "Corsair iCUE H100i Elite Capellix 240mm",
    categoria: "Refrigeracion",
    marca: "corsair",
    precioNormal: 159990,
    precioDescuento: 139990,
    stock: 9,
    destacado: false,
    imagen: "../img/productos/corsair-h100i-elite-capellix.png",
    imagenes: ["../img/productos/corsair-h100i-elite-capellix.png", "../img/productos/corsair-h100i-elite-capellix-2.png"],
    especificaciones: [
      "Radiador de 240mm, refrigeración líquida AIO",
      "2 ventiladores ML120 RGB incluidos",
      "Bomba con 33 LED tipo Capellix",
      "Software iCUE para control de curvas y RGB",
    ],
    resenas: [
      { autor: "Sebastián", puntuacion: 4, comentario: "Baja muy bien las temperaturas, la instalación toma tiempo.", fecha: "2026-05-08" },
    ],
  },
  {
    id: 13,
    nombre: "PC Armado GameHub Ryzen 5 Edition",
    categoria: "PCs-Armados",
    marca: "gamehub",
    precioNormal: 899990,
    precioDescuento: 799990,
    stock: 5,
    destacado: true,
    imagen: "../img/productos/pc-armado-ryzen-5-edition.png",
    imagenes: ["../img/productos/pc-armado-ryzen-5-edition.png", "../img/productos/pc-armado-ryzen-5-edition-2.png"],
    especificaciones: [
      "Procesador AMD Ryzen 5 7600 (6 núcleos, hasta 5.1 GHz)",
      "Tarjeta gráfica NVIDIA GeForce RTX 4060 8GB",
      "16 GB RAM DDR5 6000MHz",
      "SSD NVMe 1TB",
      "Ensamblado y probado por GameHub Store, incluye 1 año de garantía",
    ],
    resenas: [
      { autor: "Matías", puntuacion: 5, comentario: "Llegó armado, probado y listo para jugar. Excelente relación precio/rendimiento.", fecha: "2026-06-20" },
    ],
  },
];